[package]
name = "bitrepr"
version = "0.1.0"
edition = "2024"
description = "Traits and derives for packing/unpacking values into bits"
repository = "https://github.com/hazelwiss/bitrepr"
categories = ["compression", "emulators", "no-std"]
keywords = ["minimal", "no_std", "utility", "bitfields"]
license-file = "LICENSE"
readme = "README.md"

[dependencies]
bitrepr-macros = { version = "0.1.0",  path = "macros" }

[workspace]
members = ["macros"]

[profile.test]
opt-level = 2
